"""empty message

Revision ID: 50e00e2b3d46
Revises: 
Create Date: 2024-12-27 04:13:53.184183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50e00e2b3d46'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('router',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('model_name', sa.String(length=256), nullable=False),
    sa.Column('ip_address', sa.String(length=256), nullable=False),
    sa.Column('hostname', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_router_id'), 'router', ['id'], unique=False)
    op.create_table('personal_computer',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ip_address', sa.String(length=256), nullable=False),
    sa.Column('hostname', sa.String(length=256), nullable=False),
    sa.Column('router_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['router_id'], ['router.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hostname')
    )
    op.create_index(op.f('ix_personal_computer_id'), 'personal_computer', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_personal_computer_id'), table_name='personal_computer')
    op.drop_table('personal_computer')
    op.drop_index(op.f('ix_router_id'), table_name='router')
    op.drop_table('router')
    # ### end Alembic commands ###
