"""empty message

Revision ID: 87f55314ce5b
Revises: f522eba0f7e2
Create Date: 2025-05-22 06:15:37.256896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87f55314ce5b'
down_revision: Union[str, None] = 'f522eba0f7e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proces_log', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proces_log', 'created_at')
    # ### end Alembic commands ###
