"""empty message

Revision ID: b0261e4e8913
Revises: c8d294e8569f
Create Date: 2025-04-06 17:46:51.158813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0261e4e8913'
down_revision: Union[str, None] = 'c8d294e8569f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('router', sa.Column('group_name', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('router', 'group_name')
    # ### end Alembic commands ###
