"""empty message

Revision ID: c8d294e8569f
Revises: d8689e45aae8
Create Date: 2025-02-24 21:38:26.667800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8d294e8569f'
down_revision: Union[str, None] = 'd8689e45aae8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('package_log', sa.Column('web_host_name', sa.String(length=256), nullable=True))
    op.add_column('package_log', sa.Column('pc_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'package_log', 'personal_computer', ['pc_id'], ['id'], ondelete='CASCADE')
    op.drop_column('package_log', 'host_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('package_log', sa.Column('host_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'package_log', type_='foreignkey')
    op.drop_column('package_log', 'pc_id')
    op.drop_column('package_log', 'web_host_name')
    # ### end Alembic commands ###
