"""empty message

Revision ID: d2457bec7649
Revises: 29429b97e19e
Create Date: 2025-05-22 08:23:21.319252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2457bec7649'
down_revision: Union[str, None] = '29429b97e19e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('warning', 'ip_address')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warning', sa.Column('ip_address', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
