"""empty message

Revision ID: d8689e45aae8
Revises: 50e00e2b3d46
Create Date: 2025-02-24 21:06:45.712293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8689e45aae8'
down_revision: Union[str, None] = '50e00e2b3d46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('package_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('message', sa.String(length=512), nullable=True),
    sa.Column('ip_source', sa.String(length=256), nullable=False),
    sa.Column('ip_destination', sa.String(length=256), nullable=False),
    sa.Column('mac_source', sa.String(length=256), nullable=False),
    sa.Column('mac_destination', sa.String(length=256), nullable=False),
    sa.Column('port_source', sa.String(length=256), nullable=False),
    sa.Column('port_destination', sa.String(length=256), nullable=False),
    sa.Column('host_name', sa.String(length=256), nullable=True),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_package_log_id'), 'package_log', ['id'], unique=False)
    op.add_column('router', sa.Column('color', sa.String(length=8), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('router', 'color')
    op.drop_index(op.f('ix_package_log_id'), table_name='package_log')
    op.drop_table('package_log')
    # ### end Alembic commands ###
