"""empty message

Revision ID: f522eba0f7e2
Revises: b0261e4e8913
Create Date: 2025-05-22 04:57:08.825961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f522eba0f7e2'
down_revision: Union[str, None] = 'b0261e4e8913'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proces_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('pred', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proces_log_id'), 'proces_log', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proces_log_id'), table_name='proces_log')
    op.drop_table('proces_log')
    # ### end Alembic commands ###
